CREATE TABLE IF NOT EXISTS HabitType (
HabitTypeID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
HabitTypeName TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS HabitEntry (
HabitID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
HabitTypeID INTEGER NOT NULL,
HabitDescription TEXT,
HabitDateTime TEXT NOT NULL,
HabitDuration INTEGER NOT NULL,
HabitDurationUnit TEXT NOT NULL,
FOREIGN KEY(HabitTypeID) REFERENCES HabitType(HabitTypeID) ON DELETE SET NULL);